name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      
      
      #- name: Get Sharedutils
      #  uses: Silverlan/mathutil_gitactions_test/get_submodule@main
      
      
      
      
      
      #- name: Test Subaction A
      #  uses: Silverlan/mathutil_gitactions_test/testaction_a@main
        
      - name: Download submodule - GLM 0.9.9.8
        uses: Silverlan/mathutil_gitactions_test/curl_download@main
        with:
          download_url: 'https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip'
          file_name: 'glm-0.9.9.8.zip'
        
        
        
      - name: Test Subaction
        uses: Silverlan/mathutil_gitactions_test/get_submodule@main
        with:
          repo: 'https://github.com/Silverlan/sharedutils.git'
          repo_name: 'sharedutils'
          should_build: false






      #- name: Download submodule - sharedutils
      #  run: |
      #    mkdir external_libs
      #    cd external_libs
      #    git clone https://github.com/Silverlan/sharedutils.git
      #    cd sharedutils
      #    git checkout master
          
      #- name: Build submodule - sharedutils
      #  run: |
      #    cmake -S . -B . -DDEPENDENCY_GLM_INCLUDE=${{ github.workspace }}\third_party_libs\glm -DSHAREDUTILS_STATIC=ON -DDEPENDENCY_MATHUTIL_INCLUDE=${{ github.workspace }}\include\ -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"
      #    cmake --build ./ --config ${{ matrix.config.build_type }}
      #    cd ../
      
      - name: CMake Build
        uses: Silverlan/mathutil_gitactions_test/build_generic@main
        with:
          build_type: ${{ matrix.config.build_type }}
          build_generator: ${{ matrix.config.generators }}
          cmake_definitions: -DDEPENDENCY_GLM_INCLUDE=./third_party_libs/glm -DDEPENDENCY_SHAREDUTILS_INCLUDE=./external_libs/sharedutils/include -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DMATHUTIL_ENABLE_MESH_FUNCTIONS=OFF -DMATHUTIL_STATIC=ON
      

      #- name: CMake
      #  shell: bash
      #  run: |
      #    mkdir build
      #    mkdir instdir
      #    cmake \
      #      -S . \
      #      -B . \
      #      -DDEPENDENCY_GLM_INCLUDE=./third_party_libs/glm \
      #      -DDEPENDENCY_SHAREDUTILS_INCLUDE=./external_libs/sharedutils/include \
      #      -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
      #      -DMATHUTIL_ENABLE_MESH_FUNCTIONS=OFF \
      #      -DMATHUTIL_STATIC=ON \
      #      -G "${{ matrix.config.generators }}" \
      #      -DCMAKE_INSTALL_PREFIX:PATH=instdir
      #- name: Build
      #  shell: bash
      #  run: cmake --build ./ --config ${{ matrix.config.build_type }}
        
