name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download submodule - GLM 0.9.9.8
        run: |
          mkdir third_party_libs
          cd third_party_libs
          
          curl -LJO https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
          7z x glm-0.9.9.8.zip
          cd ../
          if exist "${{ github.workspace }}\third_party_libs\glm\glm\exponential.hpp" (echo "EXISTS!")
          
      - name: Download submodule - sharedutils
        run: |
          mkdir external_libs
          cd external_libs
          git clone https://github.com/Silverlan/sharedutils.git
          cd sharedutils
          git checkout master
          
      #- name: Build submodule - sharedutils
      #  run: |
      #    cmake -S . -B . -DDEPENDENCY_GLM_INCLUDE=${{ github.workspace }}\third_party_libs\glm -DSHAREDUTILS_STATIC=ON -DDEPENDENCY_MATHUTIL_INCLUDE=${{ github.workspace }}\include\ -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -G "${{ matrix.config.generators }}"
      #    cmake --build ./ --config ${{ matrix.config.build_type }}
      #    cd ../

      - name: CMake
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DDEPENDENCY_GLM_INCLUDE=${{ github.workspace }}\third_party_libs\glm \
            -DDEPENDENCY_SHAREDUTILS_INCLUDE=${{ github.workspace }}\external_libs\sharedutils\include \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DMATHUTIL_STATIC=ON \
            -G "${{ matrix.config.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build ./ --config ${{ matrix.config.build_type }}
        
